### ISSUE TITLE
运行失败但无调试信息--司法摘要

### ISSUE THREAD

**Issue by gaozhiguang** [china-ai-law-challenge/CAIL2021#2]
司法摘要评测，提交后显示运行失败，下载的调试信息.txt是空白，这个是什么原因

**Comment by aicodex** [comment]
> 司法摘要评测，提交后显示运行失败，下载的调试信息.txt是空白，这个是什么原因

首先建议按照官方提供的环境中与你最相近的环境，安装一个一模一样的环境。如果差异过大可以提交环境申请。

然后在相同环境中运行你的main.py，输入是官方第一阶段的数据，看看能否正确执行。

最后可以重新打包提交试试。

日志空白的问题，目前正在排查。

**Comment by aicodex** [comment]
> 司法摘要评测，提交后显示运行失败，下载的调试信息.txt是空白，这个是什么原因

调试功能应该已经修复了，辛苦再次提交代码。之前好像是有一些问题。
